void status(dir* d) ;
void double_dir(dir* d , int overflow) ;
int insert(dir* d , int n) ;
int search(dir* d , int val) ;
int delete(dir* d , int val) ;
int merge_buckets(dir* d , int val) ;
int lazy_delete(dir* d , int val) ;
int mirror(dir* d , int of) ;
int merge_buckets(dir* d , int val) ;
int merge(dir* d , int bid) ;
int compress_dir(dir* d , int val) ;